### ISSUE TITLE
./ffmpeg_setup.sh: line 2: ../../ffmpeg/configure: No such file or directory

### ISSUE THREAD

**Issue by lunzueta** [banderlog/opencv-python-inference-engine#1]
I get this error when running the command: bash ./ffmpeg_setup.sh
There's not such configure file in that folder. What should I do?

**Comment by banderlog** [comment]
Did you download ffmpeg and unpack it to corresponding ffmpeg folder?

**Comment by lunzueta** [comment]
OK, sorry, I missed that part. My fault.
