### ISSUE TITLE
ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found, Debian 10

### ISSUE THREAD

**Issue by Kulikovpavel** [banderlog/opencv-python-inference-engine#14]
After update to 4.5.0 version, i have this error when im trying to import cv2

`ImportError: /lib/x86_64-linux-gnu/libm.so.6: version GLIBC_2.29 not found (required by /home/xxx/.local/lib/python3.7/site-packages/cv2/cv2.so)`

Debian GNU/Linux 10 (buster)

**Comment by Kulikovpavel** [comment]
This is how i fix it

`
echo "deb http://ftp.us.debian.org/debian testing main contrib non-free" >> /etc/apt/sources.list
apt update
apt install gcc-8-base -y
apt install build-essential -y
`

But i feel that this is too much (this one installs python3.8 as default interpreter in system)

**Comment by banderlog** [comment]
It looks like I built the last release on Ubuntu 20.04 instead of 18.04, my bad. I'll recompile and upload it next 24 hours

**Comment by banderlog** [comment]
done
