### ISSUE TITLE
Why "git reset --hard 562e301"?

### ISSUE THREAD

**Issue by lunzueta** [banderlog/opencv-python-inference-engine#2]
Why that step for the installation of ADE? It would be great if the instructions would give some explanation about it. Thanks

**Comment by banderlog** [comment]
Simply because original `dldt` repository contains thirdparty repo of `ade` as submodule and it is set to #562e301 commit.

Instead of using `dldt` release in archive, you could do `git clone --recursive https://github.com/opencv/dldt`

**Comment by lunzueta** [comment]
Sorry, maybe I had to add to my question why that specific commit when the latest commit of ADE is #cbe2db6.

**Comment by banderlog** [comment]
Well, I did some research and #562e301 is the penultimate commit. The [next one](https://github.com/opencv/ade/commit/cbe2db61a659c2cc304c3837406f95c39dfa938e) (and latest at the moment) fixes only 1 number url of googletest archive (patch version of it).

**Comment by lunzueta** [comment]
OK, understood. Thanks for the explanation.
