### ISSUE TITLE
Ubuntu16.04 Support?

### ISSUE THREAD

**Issue by ohlr** [banderlog/opencv-python-inference-engine#3]
I get this error in Ubuntu 16.04 : 

`import cv2`

```
from .cv2 import *
ModuleNotFoundError: No module named 'cv2
```

Python 3.7.3
Environment: Conda

**Comment by banderlog** [comment]
I'll test it on virtual machine and will write you back.

Meanwhile, you could try to find its installation path (it will be somewhere in `conda/pkgs/opencv-python-inference-engine-4.1.0.3-*/lib/python3.7/site-packages/opencv-python-inference-engine`) and rename `cv2.cpython-36m-x86_64-linux-gnu.so` to `cv2.so`

**Comment by banderlog** [comment]
To avoid above error:

```
cd ~/.local/lib/python3.7/site-packages/cv2
mv cv2.cpython-36m-x86_64-linux-gnu.so cv2.so
```

But you will encounter the next one, about `GLIBC_2.27` not found.
And Ubuntu 16.04 does not have simple way to install it, thus, unless you will find a way to do that, there is no Ubuntu16.04 support out of box.

Of course, you could build it from sources and it should work.

**Comment by ohlr** [comment]
Thanks for clarification - will build from source now.. Is there a way to add Ubuntu 16.04 support? In the [opencv-python](https://github.com/skvark/opencv-python#manylinux-wheels ) repo they use a older version of glibc right?

**Comment by banderlog** [comment]
Yeah, they are building it with manylinux1 policy. You could find more details about it here: https://www.python.org/dev/peps/pep-0513/#the-manylinux1-policy

And there are my thoughts why I do not want to do so:
https://github.com/banderlog/opencv-python-inference-engine#not-really-manylinux1

**Comment by ohlr** [comment]
One thing I noticed:  [here](https://github.com/banderlog/opencv-python-inference-engine/blob/master/build/opencv/opencv_setup.sh) you assume that the default python3 version is 3.6. Mine was 3.5 thus cv2 was compiled without python .so.

**Comment by banderlog** [comment]
>you assume that the default python3 version is 3.6. Mine was 3.5 thus cv2 was compiled without python .so.

Yeah, you are right, for now I updated README to clear it out. Later I'll do something to automatize it.

Also, config's output provides a lot of useful info about what it found and supposed to compile. Sometimes it is not what you intended to [:

Furthermore, on second thought I decided to build python package using Ubuntu 16.04 linux container. I'll do some comparison benchmark tests and if there will be no significant difference, I'll put this package as a new version.

**Comment by banderlog** [comment]
Try this [opencv_python_inference_engine-4.1.0.4-cp35-cp35m-manylinux1_x86_64.whl](https://test-files.pythonhosted.org/packages/4c/a5/1f58ae29bbd37e59c0821bdaef7c7ba84fcd753dbc3ea6f0c78ebfe7dcba/opencv_python_inference_engine-4.1.0.4-cp35-cp35m-manylinux1_x86_64.whl) (it is from TestPyPI )

**Comment by banderlog** [comment]
Done
