### ISSUE TITLE
.so files with other pip packages

### ISSUE THREAD

**Issue by Kulikovpavel** [banderlog/opencv-python-inference-engine#4]
This package installs .SO in dirs, paraller with default opencv-python packages

```
ls /home/user/.local/lib/python3.7/site-packages/cv2/  
cv2.cpython-37m-x86_64-linux-gnu.so
cv2.so
```

And this is leads to errors when using, because other file is used for import, from other versions

Is it possible to mimic naming of that .so file?

**Comment by banderlog** [comment]
Well, the package was not intended to be used in parallel with other OpenCV packages. But you can try to compile your own python package, using this repo,  with renamed `.so` file and edited `__init__.py`.

**Comment by hello-binit** [comment]
Hi all, just a FYI, I needed to use this package in parallel with the [contrib OpenCV package](https://pypi.org/project/opencv-contrib-python/), so I ended following @banderlog's suggestion here and recompiled the package under a different name. The changes are [in my fork](https://github.com/hello-binit/renamed-opencv-python-inference-engine/), and the package is [released on PyPi](https://pypi.org/project/renamed-opencv-python-inference-engine/). Once installed, the package is used via `import renamed_cv2`. Thank you @banderlog for the clear compilation instructions.
