### ISSUE TITLE
opencv with CUDA ON

### ISSUE THREAD

**Issue by chad-green** [banderlog/opencv-python-inference-engine#9]
The cv2.dnn module with cuda support is a game changer, but to use it with IR models, you need to build with the inference engine from openvino. You mentioned that you haven't tried compiling your library with opencv and cuda support yet. I've been struggling to get both openvino and opencv working together. If you get a pywheel with both, that would be amazing! Any thoughts on when you might try that?

**Comment by banderlog** [comment]
From https://github.com/banderlog/opencv-python-inference-engine/issues/7#issuecomment-632003525
>**On the CUDA**
>
>I will not build a separate package with CUDA support, it is meaningless. There few versions of CUDA and CUDNn libraries with different combinations for different GPUs and there is no way to compile OpenCV in a way when it will support them all. And you will need to download CUDA/CUDNn libraries from nvidia manually -- no "an ability to fast deploy a small package" here.
Also, I wanted this package for CPU inference only.
Here is an excellent guide how to compile OpenCV with CUDA: https://www.pyimagesearch.com/2020/02/03/how-to-use-opencvs-dnn-module-with-nvidia-gpus-cuda-and-cudnn/

**Comment by banderlog** [comment]
It could work if OpenCV's CUDA API does not depend on CUDA version. In such case I could build a library which is able to work with CUDA if it is properly installed in a system.

> I've been struggling to get both openvino and opencv working together.

OpenVINO has OpenCV inside. In fact, it is just an OpenCV build with dldt and model optimizer. Also it ships with proprietary linear algebra library. Maybe few things more now.

**Comment by chad-green** [comment]
No, you're right, you have to have cuDNN installed and you have to give the correct CUDA_ARCH_BIN flag associated with your GPU during the OpenCV build. Wishful thinking, unfortunately. Thank you for your work, though. Nice to have this ready for CPU.
